# Generated by Django 6.0.4 on 2026-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="reservation_duration_minutes",
            field=models.IntegerField(default=90),
        ),
    ]
