# Generated by Django 6.0.4 on 2026-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="reservation_slot_minutes",
            field=models.IntegerField(default=30),
        ),
    ]
