# Generated by Django 6.0.4 on 2026-07-14 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_restaurant_reservation_slot_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="reservation_duration_minutes",
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="reservation_slot_minutes",
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
