# Generated by Django 6.0.4 on 2026-07-14 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_alter_restaurant_reservation_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="reservation_slot_minutes",
            new_name="reservation_interval_minutes",
        ),
    ]
