# Generated by Django 6.0.4 on 2026-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0006_restaurant_no_show_ban_threshold_restaurantban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantban",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
