# Generated by Django 6.0.4 on 2026-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_rules", "0001_initial"),
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availablerule",
            constraint=models.UniqueConstraint(fields=("restaurant", "day_of_week"), name="unique_day_of_week"),
        ),
    ]
