# Generated by Django 6.0.4 on 2026-05-21 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_rules", "0002_availablerule_unique_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restauranttable",
            name="seats",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
