# Generated by Django 6.0.4 on 2026-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_rules", "0003_alter_restauranttable_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantbreak",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=2,
            ),
            preserve_default=False,
        ),
    ]
