# Generated by Django 6.0.4 on 2026-07-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_rules", "0004_restaurantbreak_day_of_week"),
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantbreak",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_breaks",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="restauranttable",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_tables",
                to="restaurants.restaurant",
            ),
        ),
    ]
