# Generated by Django 6.0.4 on 2026-07-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("available_rules", "0005_alter_restaurantbreak_restaurant_and_more"),
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurantexception",
            constraint=models.UniqueConstraint(fields=("restaurant", "date"), name="unique_date_per_restaurant"),
        ),
    ]
