# Generated by Django 6.0.4 on 2026-05-09 14:40

from django.db import migrations, models

import accounts.utilis


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.CharField(default=accounts.utilis.generate_verification_code, max_length=6, unique=True),
        ),
    ]
