# Generated by Django 6.0.4 on 2026-05-27 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberShip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("manager", "Manager"), ("staff", "Staff")], max_length=7)),
                (
                    "restaurant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "restaurant"), name="unique_membership")],
            },
        ),
    ]
