# Generated by Django 6.0.4 on 2026-05-28 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0001_initial"),
        ("restaurants", "0002_restaurant_reservation_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="restaurants.restaurant"
            ),
        ),
    ]
