# Generated by Django 6.0.4 on 2026-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
