# Generated by Django 6.0.4 on 2026-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
