# Generated by Django 6.0.4 on 2026-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
