# Generated by Django 6.0.4 on 2026-07-15 17:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_system", "0002_booking_end_time_alter_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
