# Generated by Django 6.0.4 on 2026-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_system", "0003_alter_booking_confirmation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No_show"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
